### ISSUE TITLE
Error generating files while compiling GPU Utils

### ISSUE THREAD

**Issue by tillepprecht** [3dem/relion#1315]
**Describe your problem**

Hi I'm trying to build relion 5.0.1 for our processing worksation, but I keep running into errors early on in the compile process, when gpu util and other nvcc things are getting built.

**Environment:**
 - OS: Ubuntu 24.0.4 LTS
 - MPI runtime: mpiexec (OpenRTE) 4.1.6
 - RELION version: git branch origin/ver5.0
 - Memory: 512 GB
 - GPU: 2x RTX5090 (580.105.08, CUDA 13.0)
 - cmake: 3.26.4, also tried with 3.28 first
 - nvcc --version: Cuda compilation tools, release 13.0, V13.0.88
 - mpicxx --version: g++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0

**Commands used:**

```
git clone https://github.com/3dem/relion.git
cd ~/relion
git checkout ver5.0
git pull

conda env create -f environment_blackwell.yaml (here I also tried with installing torch=2.9.0 and torchvision with cu130, lead to same issue)

mkdir build
cd build
cmake -DCUDA_ARCH=120 -DFORCE_OWN_FFTW=ON -DAMDFFTW=ON .. (here I tried with and without the AMD specific flags, and also with and without the -DCUDA_ARCH flag, same error everytime)
make -j 24 (here I also tried -j 1, -j 8, same error everytime)
```
The compilation of FFTW seems to run well, but then it fails when getting to the first nvcc stuff.

From what I can tell during the cmake command, it finds the correct CUDA version, and CUDA home and everything, but then still fails when trying to build something with nvcc.

Any ideas what I should try next?

**Error message:**

```
[  0%] Built target copy_scripts
[  0%] Linking CXX static library ../../lib/librelion_jaz_gpu_util.a
[  1%] Built target relion_jaz_gpu_util
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = __builtin_new_allocator::__builtin_new_deleter]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
   31 | _CCCL_NODISCARD _LIBCUDACXX_HIDE_FROM_ABI constexpr _Tp&& forward(remove_reference_t<_Tp>& __t) noexcept
      | ^~~~~~~
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = void*&]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = int]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = cudaError]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = cub::CUB_300001_SM_1200::SmVersion(int&, int)::<lambda(int&)>]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = cub::CUB_300001_SM_1200::PtxVersion(int&, int)::<lambda(int&)>]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/move.h: In instantiation of ‘constexpr cuda::std::__4::remove_reference_t<_Tp>&& cuda::std::__4::move(_Tp&&) [with _Tp = __builtin_new_allocator::__builtin_new_deleter&]’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__utility/move.h:32:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
   32 | _CCCL_NODISCARD _LIBCUDACXX_HIDE_FROM_ABI constexpr remove_reference_t<_Tp>&& move(_Tp&& __t) noexcept
      | ^~~~
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280 (message):
  Error generating file
  ~/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o


make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:7898: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:389: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**cmake output:**
```
Make Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "13.0") 
-- Using provided CUDA_ARCH=120
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- CMAKE_CXX_COMPILER_ID : GNU
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Could NOT find FLTK (missing: FLTK_LIBRARIES FLTK_INCLUDE_DIR) 
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: ~/relion/external/fltk/include
-- FLTK_LIBRARIES:   ~/relion/external/fltk/lib/libfltk.so
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.5.1")  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.3.#define ZLIB_VERSION "1.3"")  
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.43") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Will try to find Conda environment (name: relion-5.0) and its Python executable...
-- Found Conda executable: ~/miniforge3/bin/conda
-- Found Conda environment (name: relion-5.0) and its Python executable.
-- Using Python executable: ~/miniforge3/envs/relion-5.0/bin/python
-- Will try to find Torch home directory...
-- Using Torch home: ~/.cache/torch
-- Will attempts to download model weights for dependent packages...
NOTE: You can skip this step by setting -DFETCH_WEIGHTS=OFF
Attempting to download weights for class ranker...
Model (v1.0) loaded successfully from checkpoint ~/.cache/torch/hub/checkpoints/relion_class_ranker/v1.0.ckpt
No project directory was specified... exiting!
Attempting to download weights for Blush...
Blush model (v1.0) loaded successfully from checkpoint ~/.cache/torch/hub/checkpoints/relion_blush/v1.0.ckpt
No job target was specified for Blush regularization... exiting!
Attempting to download weights for ModelAngelo...
~/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/torch/backends/__init__.py:46: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:80.)
  self.setter(val)
Please make sure you have set the environment variable TORCH_HOME 
to a suitable directory, visible to all relevant users!
Successful!
Path to model is ~/.cache/torch/hub/checkpoints/model_angelo_v1.0/nucleotides
~/miniforge3/envs/relion-5.0/lib/python3.10/site-packages/torch/backends/__init__.py:46: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:80.)
  self.setter(val)
Please make sure you have set the environment variable TORCH_HOME 
to a suitable directory, visible to all relevant users!
Successful!
Path to model is ~/.cache/torch/hub/checkpoints/model_angelo_v1.0/nucleotides_no_seq
-- Successfully downloaded model weights
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:~/relion/build
-- Git commit ID: 73f0a3c0c9dfa513ca0456ef8f66dd3eb5c35cdb
-- CMAKE_C_FLAGS : -std=c99  -fopenmp
-- CMAKE_CXX_FLAGS : -fPIC -std=c++17  -fopenmp
-- Configuring done (7.9s)
-- Generating done (0.3s)
-- Build files have been written to: ~/relion/build
```

**Comment by biochem-fan** [comment]
This error looks similar to https://github.com/3dem/relion/issues/1313, where I thought this was specific to Fedora 41 and decided to ignore. But if this happens on Ubuntu as well, I have to investigate again.

My current understanding is that this is caused by libcu++'s incompatibility with the system compiler. This happens only when the code uses NCCL.

**Comment by biochem-fan** [comment]
I reproduced your problem.

`nvcc release 13.0, V13.0.48` worked fine on Ubuntu 22.04 LTS with GCC 11.4.0 but failed with your error on Ubuntu 24.04 LTS with GCC 13.3.0.

**Comment by biochem-fan** [comment]
I fixed the problem. Please pull the latest commit, delete your build directory and start again from `cmake`.

This problem occurred with GCC >= 13 (? 11 is OK, 12 not tested).
NVIDIA updated its `libcudacxx` headers to avoid this issue:
https://github.com/NVIDIA/cccl/blob/318408d1aa3b4f892ea417ab0363d4d67cd4282c/libcudacxx/include/cuda/std/__type_traits/remove_reference.h#L36-L43

RELION, however, disguised GCC as Intel Compiler (commit 0519509) and the above NVIDIA fix was not activated. This was the root cause.

The disguise was introduced 10 years ago as a workaround for [a compatibility issue](https://github.com/FFTW/fftw3/issues/18) between FFTW3 and an old `nvcc` that did not support float128. Because modern `nvcc` supports `float128`, this ugly hack is no longer necessary. I removed this disguise and the problem was solved :)

**Comment by tillepprecht** [comment]
Thank you so much for the quick resolution, I can confirm that it compiles without issues now :)
